import { Suspense } from 'react';
import { Canvas } from '@react-three/fiber';
import { useGLTF, Environment, OrbitControls } from '@react-three/drei';

// Generated by blender-cinematic-agent-skill. Place scene.glb in /public.
function Model() {
  const { scene, animations } = useGLTF('/scene.glb');
  return <primitive object={scene} />;
}
useGLTF.preload('/scene.glb');

export default function Scene() {
  return (
    <Canvas dpr={[1, 2]} camera={{ position: [0, 1, 4], fov: 50 }}>
      <Suspense fallback={null}>
        <ambientLight intensity={0.6} />
        <Model />
        <Environment preset="studio" />
        <OrbitControls makeDefault />
      </Suspense>
    </Canvas>
  );
}
